version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node-browsers
        environment:
          - PG_HOST=127.0.0.1
          - PG_USER=rails_blog_test
          - RAILS_ENV=test
          - RACK_ENV=test
          - DEFAULT_URL_HOST=http://localhost:5000

      - image: circleci/postgres:9.6
        environment:
          - POSTGRES_USER=myapp
          - POSTGRES_DB=rails_blog_test

    steps:
      - checkout

      - run:
          name: Install Chrome
          command: |
            sudo apt-get install libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb

      - restore_cache:
          name: Restore bundle cache
          keys:
            - myapp-bundle-{{ checksum "Gemfile.lock" }}
            - myapp-bundle-

      - run:
          name: Install Ruby dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: Store bundle cache
          key: myapp-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://myapp@localhost:5432/rails_blog_test"

      - run: mkdir ~/rspec

      - run:
          name: Run rspec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
          environment:
            DATABASE_URL: "postgres://myapp@localhost:5432/rails_blog_test"

      - run:
          name: Rubocop
          command: rubocop

      - store_test_results:
          path: ~/rspec

      - store_artifacts:
          path: ~/rspec
          destination: rails_blog
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master